#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
UI="$ROOT/PrivateMessaging.qml"
PANEL="$ROOT/Panel.qml"

# Private messaging stays a separate, capability-gated text surface.
grep -q 'privateSendAvailable' "$UI"
grep -q 'sendPrivateMessage' "$UI"
! grep -q 'New message' "$UI"
! grep -q 'recipientField' "$UI"
grep -q 'leftAlias.*toLowerCase' "$UI"
grep -q 'peerDirectoryAvailable' "$UI"
grep -q 'knownPeers' "$UI"
grep -q '"Search direct messages"' "$UI"
grep -q 'filterMessages(conversationMessages, messageQuery)' "$UI"
grep -q 'property bool searchOpen: false' "$UI"
grep -q 'visible: root.searchOpen' "$UI"
grep -q 'privateSurface.toggleSearch()' "$PANEL"
! grep -q 'shortKey' "$UI"
grep -q 'parent.width \* 0.46' "$UI"
grep -q 'Layout.preferredWidth: 1' "$UI"
! grep -q 'UNTRUSTED ALIAS' "$UI"
grep -q 'text: "No peers"' "$UI"
grep -q '"No matching messages"' "$UI"
grep -q 'Layout.alignment: Qt.AlignLeft' "$UI"
grep -q 'Qt.formatTime(new Date(Number(modelData.timestampMs' "$UI"
grep -q 'id: composer' "$UI"
grep -q 'PanelSeparator {' "$UI"
! grep -q 'text: root.value("privateSending", false) ? "Sending…" : "Send"' "$UI"
grep -q 'modelData.online' "$UI"
! grep -q 'addressed to the canonical peer key' "$UI"
! grep -Eq 'attachment|delivered|delivery|read receipt|end-to-end' "$UI"

# Entry points, compact drill-in, help, navigation, and IPC remain discoverable.
grep -q 'sequence: "Ctrl+D"' "$PANEL"
grep -q 'function privateMessages()' "$PANEL"
grep -q 'compact: root.panelWidthPercent === 25' "$PANEL"
grep -q 'root.compact && root.detailOpen' "$UI"
grep -q 'moveSelection' "$UI"
grep -q 'unreadCount' "$UI"
grep -q 'id: privateRotation' "$PANEL"
grep -q 'visible: root.privateOpen || privateRotation.angle < 89.9' "$PANEL"
grep -q 'angle: root.privateOpen ? 0 : 90' "$PANEL"
grep -q 'sequence: "Ctrl+Alt+C"' "$PANEL"
grep -q 'copyFocusedMessage()' "$PANEL"
grep -q 'messageCopyNotice = "Message copied"' "$PANEL"
grep -q 'sequence: "Ctrl+Delete"' "$PANEL"
grep -q 'deleteFocusedMessage()' "$PANEL"
grep -q 'mesh.removeMessage(item.id)' "$PANEL"
grep -q 'id: messageCopyNoticeClear' "$PANEL"

echo 'private messaging UI tests: PASS'
